// All exercise pictures by exercise id (src/catalog.ts). An exercise without its own picture (the trainer's own)
// gets one of its muscle group: pictureFor in figure/index.tsx.
import type { Move } from './kit';
import type { FrontMove } from './front';
import * as front from './front';
import * as chest from './chest';
import * as back from './back';
import * as legs from './legs';
import * as arms from './arms';
import * as shoulders from './shoulders';
import * as abs from './abs';

export type { Move };
export type AnyMove = Move | FrontMove;

export const MOVES: Record<string, AnyMove> = {
  // chest
  'bench-press': chest.benchPress,
  'incline-dumbbell-press': chest.inclineDumbbellPress,
  'smith-incline-press': chest.smithInclinePress,
  'machine-chest-press': chest.machineChestPress,
  'stack-chest-press': chest.machineChestPress,
  'plate-chest-press': chest.plateChestPress,
  'plate-incline-press': chest.plateInclinePress,
  'cable-fly': chest.cableFly,
  'pec-deck': chest.pecDeckMove,
  'stack-pec-fly': chest.pecDeckMove,
  dips: chest.dipsMove,
  'stack-assisted-dip': chest.assistedDips,
  // back
  'lat-pulldown': back.latPulldown,
  'stack-lat-pulldown': back.stackPulldown,
  'plate-lat-pulldown': back.platePulldown,
  'pull-up': back.pullUpMove,
  'assisted-pull-up': back.assistedPullUp,
  'seated-row': back.seatedRow,
  'stack-seated-row': back.stackSeatedRow,
  'plate-seated-row': back.plateSeatedRow,
  'plate-low-row': back.plateLowRow,
  'barbell-row': back.barbellRow,
  'one-arm-row': back.oneArmRow,
  'back-extension': back.backExtensionMove,
  'stack-back-extension': back.machineBackExtension,
  'cable-pullover': back.cablePullover,
  'chest-supported-row': back.chestSupportedRow,
  't-bar-row': back.chestSupportedRow,
  'plate-dorian-row': back.dorianRow,
  'plate-shrug': back.plateShrug,
  deadlift: back.deadliftMove,
  'plate-deadlift': back.plateDeadlift,
  // legs
  'back-squat': legs.backSquat,
  'front-squat': legs.frontSquat,
  'smith-squat': legs.smithSquat,
  'hack-squat': legs.hackSquatMove,
  'pendulum-squat': legs.pendulumSquat,
  'plate-belt-squat': legs.beltSquat,
  'leg-press': legs.legPress,
  'plate-leg-press': legs.legPress,
  'stack-leg-press': legs.stackLegPress,
  'leg-press-calf': legs.legPressCalf,
  'leg-extension': legs.legExtensionMove,
  'stack-leg-extension': legs.legExtensionMove,
  'plate-leg-extension': legs.plateLegExtension,
  'leg-curl': legs.seatedLegCurl,
  'seated-leg-curl': legs.seatedLegCurl,
  'stack-seated-leg-curl': legs.seatedLegCurl,
  'lying-leg-curl': legs.lyingLegCurl,
  'stack-lying-leg-curl': legs.lyingLegCurl,
  'plate-standing-leg-curl': legs.standingLegCurl,
  rdl: legs.romanianDeadlift,
  'hip-thrust': legs.hipThrustMove,
  'plate-hip-thrust': legs.plateHipThrust,
  'bulgarian-split-squat': legs.bulgarianSplitSquat,
  'reverse-lunge': legs.reverseLungeMove,
  'plate-lunge': legs.plateLunge,
  'cable-kickback': legs.cableKickback,
  'calf-raise': legs.standingCalfRaise,
  'hip-abduction': front.hipAbduction,
  'stack-hip-abduction': front.hipAbduction,
  'hip-adduction': front.hipAdduction,
  'stack-hip-adduction': front.hipAdduction,
  // shoulders
  'lateral-raise': front.lateralRaise,
  'cable-lateral-raise': front.cableLateralRaise,
  'machine-lateral-raise': front.machineLateralRaise,
  'stack-lateral-raise': front.machineLateralRaise,
  'overhead-press': shoulders.overheadPress,
  'dumbbell-shoulder-press': shoulders.dumbbellShoulderPress,
  'machine-shoulder-press': shoulders.machineShoulderPress,
  'stack-shoulder-press': shoulders.machineShoulderPress,
  'plate-shoulder-press': shoulders.plateShoulderPress,
  'rear-delt-fly': shoulders.reverseFly,
  'reverse-pec-deck': shoulders.reverseFly,
  'stack-rear-delt': shoulders.reverseFly,
  'face-pull': shoulders.facePull,
  'standing-calf-raise': legs.standingCalfRaise,
  'seated-calf-raise': legs.seatedCalfRaise,
  // arms
  'dumbbell-curl': arms.dumbbellCurl,
  'barbell-curl': arms.barbellCurl,
  'hammer-curl': arms.hammerCurl,
  'cable-curl': arms.cableCurl,
  'bayesian-curl': arms.bayesianCurl,
  'incline-curl': arms.inclineCurl,
  'preacher-curl': arms.preacherCurl,
  'stack-biceps-curl': arms.machineCurl,
  'triceps-pushdown': arms.tricepsPushdown,
  'overhead-triceps': arms.overheadTriceps,
  'lying-triceps-extension': arms.lyingTricepsExtension,
  'stack-triceps-press': arms.stackTricepsPress,
  'plate-triceps': arms.plateTriceps,
  // abs
  crunch: abs.crunch,
  'reverse-crunch': abs.reverseCrunch,
  'cable-crunch': abs.cableCrunch,
  'hanging-leg-raise': abs.hangingLegRaise,
  'stack-ab-crunch': abs.stackAbCrunch,
  'plate-ab-crunch': abs.plateAbCrunch,
};
