import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://127.0.0.1:5173/?demo=1'); await p.waitForTimeout(2500);
const call = (m, path, body) => p.evaluate(async ([m, path, body]) => { const api = window.__tlApi; return (m === 'get' ? await api.get(path) : await api.post(path, body)).data; }, [m, path, body]);
const who = 'Ольга';
await p.locator('.nav').getByRole('button', { name: 'Зал' }).click(); await p.waitForTimeout(500);
const add = p.getByRole('button', { name: 'Отметить пришедших' }); if (await add.count()) await add.click();
await p.locator('.arrival', { hasText: who }).first().click();
await p.getByRole('button', { name: /Пришли: 1/ }).click(); await p.waitForTimeout(1500);
await p.locator('.gym-tab', { hasText: who }).first().click(); await p.waitForTimeout(800);
const pane = p.locator('.gym-pane:not([hidden])');
const progOf = async () => { const { programs } = await call('get', '/api/programs'); const { clients } = await call('get', '/api/clients'); const c = clients.find((x) => x.clientName === who); return programs.filter((x) => x.clientId === c.clientId && !x.archived); };
const before = await progOf();
const dayName = (await pane.innerText()).match(/\n([^\n]+)\nсменить/)?.[1];
console.log('day', dayName, 'programs', before.map((x) => x.name + ': ' + x.days.map((d) => d.name + '[' + d.exercises.map((e) => e.exerciseId).join(',') + ']').join(' ')));
const firstName = (await pane.locator('[aria-label^="Действия с упражнением: "]').first().getAttribute('aria-label')).replace('Действия с упражнением: ', '');
await pane.locator('[aria-label^="Действия с упражнением: "]').first().click(); await p.waitForTimeout(400);
await p.locator('.menu-item', { hasText: 'Заменить' }).first().click(); await p.waitForTimeout(800);
const sheet = p.locator('.sheet').last();
await sheet.locator('input').first().fill('Гакк'); await p.waitForTimeout(500);
await sheet.locator('.pick').first().click(); await p.waitForTimeout(500);
await p.getByRole('button', { name: 'В программе насовсем' }).click(); await p.waitForTimeout(2500);
console.log('swapped', firstName, '→ Гакк; errors on screen:', (await pane.locator('.alert, .error').allInnerTexts()).join(' | '));
const mid = await progOf();
console.log('after save', mid.map((x) => x.days.map((d) => d.name + '[' + d.exercises.map((e) => e.exerciseId).join(',') + ']').join(' ')));
// tick a set and finish
const row = pane.locator('.set-row:not(.set-labels):not(.is-done)').first();
const w = row.locator('[data-w]'); if ((await w.count()) && !(await w.inputValue())) await w.fill('40');
await row.getByRole('button', { name: /^Подход выполнен/ }).click(); await p.waitForTimeout(800);
await pane.getByRole('button', { name: /Завершить тренировку/ }).click();
await p.getByRole('button', { name: 'Завершить', exact: true }).click(); await p.waitForTimeout(2500);
const after = await progOf();
console.log('after finish', after.map((x) => x.days.map((d) => d.name + '[' + d.exercises.map((e) => e.exerciseId).join(',') + ']').join(' ')));
console.log('errors', errs);
await b.close();
