export const catalog = [
  {
    id: 'bench-press',
    name: 'Жим штанги лёжа',
    muscleGroup: 'Грудь',
    equipment: 'Штанга',
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Жим гантелей на наклонной скамье',
    muscleGroup: 'Грудь',
    equipment: 'Гантели',
  },
  {
    id: 'machine-chest-press',
    name: 'Жим в тренажёре',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'cable-fly',
    name: 'Сведение рук в кроссовере',
    muscleGroup: 'Грудь',
    equipment: 'Блок',
  },
  {
    id: 'pull-up',
    name: 'Подтягивания',
    muscleGroup: 'Спина',
    equipment: 'Собственный вес',
  },
  {
    id: 'lat-pulldown',
    name: 'Вертикальная тяга',
    muscleGroup: 'Спина',
    equipment: 'Блок',
  },
  {
    id: 'seated-row',
    name: 'Горизонтальная тяга',
    muscleGroup: 'Спина',
    equipment: 'Блок',
  },
  {
    id: 'barbell-row',
    name: 'Тяга штанги в наклоне',
    muscleGroup: 'Спина',
    equipment: 'Штанга',
  },
  {
    id: 'one-arm-row',
    name: 'Тяга гантели одной рукой',
    muscleGroup: 'Спина',
    equipment: 'Гантель',
  },
  {
    id: 'back-extension',
    name: 'Гиперэкстензия',
    muscleGroup: 'Разгибатели спины',
    equipment: 'Скамья',
  },
  {
    id: 'back-squat',
    name: 'Приседание со штангой',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Штанга',
  },
  {
    id: 'front-squat',
    name: 'Фронтальный присед',
    muscleGroup: 'Квадрицепс',
    equipment: 'Штанга',
  },
  {
    id: 'hack-squat',
    name: 'Гакк-присед',
    muscleGroup: 'Квадрицепс',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'leg-press',
    name: 'Жим ногами',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'leg-extension',
    name: 'Разгибание голени',
    muscleGroup: 'Квадрицепс',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'leg-curl',
    name: 'Сгибание голени',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'rdl',
    name: 'Румынская тяга',
    muscleGroup: 'Бицепс бедра / ягодицы',
    equipment: 'Штанга',
  },
  {
    id: 'deadlift',
    name: 'Становая тяга',
    muscleGroup: 'Задняя цепь',
    equipment: 'Штанга',
  },
  {
    id: 'hip-thrust',
    name: 'Ягодичный мост',
    muscleGroup: 'Ягодицы',
    equipment: 'Штанга',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Болгарский сплит-присед',
    muscleGroup: 'Ягодицы / квадрицепс',
    equipment: 'Гантели',
  },
  {
    id: 'reverse-lunge',
    name: 'Выпад назад',
    muscleGroup: 'Ягодицы / квадрицепс',
    equipment: 'Гантели',
  },
  {
    id: 'hip-abduction',
    name: 'Отведение бедра в тренажёре',
    muscleGroup: 'Ягодицы',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'calf-raise',
    name: 'Подъём на носки',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
  },
  {
    id: 'overhead-press',
    name: 'Жим над головой',
    muscleGroup: 'Плечи',
    equipment: 'Штанга',
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Жим гантелей сидя',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
  },
  {
    id: 'lateral-raise',
    name: 'Отведение гантелей в стороны',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
  },
  {
    id: 'rear-delt-fly',
    name: 'Разведение на заднюю дельту',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'barbell-curl',
    name: 'Сгибание рук со штангой',
    muscleGroup: 'Бицепс',
    equipment: 'Штанга',
  },
  {
    id: 'dumbbell-curl',
    name: 'Сгибание рук с гантелями',
    muscleGroup: 'Бицепс',
    equipment: 'Гантели',
  },
  {
    id: 'hammer-curl',
    name: 'Молотковые сгибания',
    muscleGroup: 'Бицепс / плечевая',
    equipment: 'Гантели',
  },
  {
    id: 'triceps-pushdown',
    name: 'Разгибание рук на блоке',
    muscleGroup: 'Трицепс',
    equipment: 'Блок',
  },
  {
    id: 'overhead-triceps',
    name: 'Разгибание рук из-за головы',
    muscleGroup: 'Трицепс',
    equipment: 'Блок',
  },
  {
    id: 'lying-triceps-extension',
    name: 'Разгибание рук лёжа',
    muscleGroup: 'Трицепс',
    equipment: 'Гантели',
  },
  {
    id: 'crunch',
    name: 'Скручивание',
    muscleGroup: 'Пресс',
    equipment: 'Собственный вес',
  },
  {
    id: 'reverse-crunch',
    name: 'Обратное скручивание',
    muscleGroup: 'Пресс',
    equipment: 'Собственный вес',
  },
  {
    id: 'seated-leg-curl',
    name: 'Сгибание голени сидя',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'lying-leg-curl',
    name: 'Сгибание голени лёжа',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'incline-curl',
    name: 'Сгибание рук на наклонной скамье',
    muscleGroup: 'Бицепс',
    equipment: 'Гантели',
  },
  {
    id: 'preacher-curl',
    name: 'Сгибание рук на скамье Скотта',
    muscleGroup: 'Бицепс',
    equipment: 'Штанга',
  },
  {
    id: 'cable-pullover',
    name: 'Пулловер на верхнем блоке',
    muscleGroup: 'Спина',
    equipment: 'Блок',
  },
  {
    id: 'chest-supported-row',
    name: 'Тяга с опорой груди',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'standing-calf-raise',
    name: 'Подъём на носки стоя',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
  },
  {
    id: 'pec-deck',
    name: 'Сведение рук в тренажёре (бабочка)',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'smith-incline-press',
    name: 'Жим в Смите на наклонной скамье',
    muscleGroup: 'Грудь',
    equipment: 'Смит',
  },
  {
    id: 'dips',
    name: 'Отжимания на брусьях',
    muscleGroup: 'Грудь / трицепс',
    equipment: 'Собственный вес',
  },
  {
    id: 'assisted-pull-up',
    name: 'Подтягивания в гравитроне',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 't-bar-row',
    name: 'Тяга Т-грифа с опорой',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'smith-squat',
    name: 'Приседание в Смите',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Смит',
  },
  {
    id: 'pendulum-squat',
    name: 'Маятниковый присед',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'hip-adduction',
    name: 'Сведение бёдер в тренажёре',
    muscleGroup: 'Приводящие бедра',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'cable-kickback',
    name: 'Отведение ноги назад в кроссовере',
    muscleGroup: 'Ягодицы',
    equipment: 'Блок',
  },
  {
    id: 'seated-calf-raise',
    name: 'Подъём на носки сидя',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'leg-press-calf',
    name: 'Подъём на носки в жиме ногами',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Жим вверх в тренажёре',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'cable-lateral-raise',
    name: 'Отведение руки на нижнем блоке',
    muscleGroup: 'Плечи',
    equipment: 'Блок',
  },
  {
    id: 'machine-lateral-raise',
    name: 'Отведение рук в тренажёре',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'reverse-pec-deck',
    name: 'Обратная бабочка',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'face-pull',
    name: 'Тяга каната к лицу',
    muscleGroup: 'Плечи',
    equipment: 'Блок',
  },
  {
    id: 'cable-curl',
    name: 'Сгибание рук на нижнем блоке',
    muscleGroup: 'Бицепс',
    equipment: 'Блок',
  },
  {
    id: 'bayesian-curl',
    name: 'Сгибание руки на блоке за спиной',
    muscleGroup: 'Бицепс',
    equipment: 'Блок',
  },
  {
    id: 'cable-crunch',
    name: 'Скручивание на блоке',
    muscleGroup: 'Пресс',
    equipment: 'Блок',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Подъём ног в висе',
    muscleGroup: 'Пресс',
    equipment: 'Собственный вес',
  },
  // Machines of our gym (Impulse IT95 stacks, Impulse ECP / Sterling / HSP plate-loaded).
  {
    id: 'stack-chest-press',
    name: 'Жим от груди со сведением (стек)',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-lat-pulldown',
    name: 'Тяга сверху рычажная (стек)',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-biceps-curl',
    name: 'Сгибание рук в тренажёре (стек)',
    muscleGroup: 'Бицепс',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-leg-extension',
    name: 'Разгибание ног (стек)',
    muscleGroup: 'Квадрицепс',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-seated-leg-curl',
    name: 'Сгибание ног сидя (стек)',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-hip-adduction',
    name: 'Сведение ног (стек)',
    muscleGroup: 'Приводящие бедра',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-hip-abduction',
    name: 'Разведение ног (стек)',
    muscleGroup: 'Ягодицы',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-leg-press',
    name: 'Жим ногами (стек)',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-shoulder-press',
    name: 'Жим от плеч со сведением (стек)',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-ab-crunch',
    name: 'Скручивания в тренажёре (стек)',
    muscleGroup: 'Пресс',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-pec-fly',
    name: 'Бабочка (стек)',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-rear-delt',
    name: 'Разведения на заднюю дельту (стек)',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-triceps-press',
    name: 'Жим на трицепс сидя (стек)',
    muscleGroup: 'Трицепс',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-seated-row',
    name: 'Гребная тяга с упором (стек)',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-assisted-dip',
    name: 'Отжимания на брусьях в гравитроне (стек)',
    muscleGroup: 'Грудь / трицепс',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-lying-leg-curl',
    name: 'Сгибание ног лёжа (стек)',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-lateral-raise',
    name: 'Махи в стороны в тренажёре (стек)',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'stack-back-extension',
    name: 'Разгибание спины в тренажёре (стек)',
    muscleGroup: 'Разгибатели спины',
    equipment: 'Тренажёр (стек)',
  },
  {
    id: 'plate-shoulder-press',
    name: 'Жим от плеч (блины)',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-chest-press',
    name: 'Жим от груди (блины)',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-lat-pulldown',
    name: 'Тяга сверху (блины)',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-seated-row',
    name: 'Гребная тяга сидя (блины)',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-ab-crunch',
    name: 'Пресс в тренажёре (блины)',
    muscleGroup: 'Пресс',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-leg-extension',
    name: 'Разгибание ног (блины)',
    muscleGroup: 'Квадрицепс',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-low-row',
    name: 'Нижняя гребная тяга рычажная (блины)',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-incline-press',
    name: 'Жим от груди под наклоном рычажный (блины)',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-leg-press',
    name: 'Жим ногами (блины)',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-triceps',
    name: 'Трицепс-машина (блины)',
    muscleGroup: 'Трицепс',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-standing-leg-curl',
    name: 'Сгибание ноги стоя (блины)',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-hip-thrust',
    name: 'Ягодичный мост в тренажёре (блины)',
    muscleGroup: 'Ягодицы',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-deadlift',
    name: 'Становая тяга в рычажном тренажёре (блины)',
    muscleGroup: 'Задняя цепь',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-shrug',
    name: 'Шраги в рычажном тренажёре (блины)',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-lunge',
    name: 'Выпады в рычажном тренажёре (блины)',
    muscleGroup: 'Ягодицы / квадрицепс',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-belt-squat',
    name: 'Приседания с поясом (блины)',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Тренажёр (блины)',
  },
  {
    id: 'plate-dorian-row',
    name: 'Тяга Дориана Ятса (блины)',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр (блины)',
  },
];
