export const catalog = [
  {
    id: 'bench-press',
    name: 'Жим штанги лёжа',
    muscleGroup: 'Грудь',
    equipment: 'Штанга',
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Жим гантелей на наклонной скамье',
    muscleGroup: 'Грудь',
    equipment: 'Гантели',
  },
  {
    id: 'machine-chest-press',
    name: 'Жим в тренажёре',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр',
  },
  {
    id: 'cable-fly',
    name: 'Сведение рук в кроссовере',
    muscleGroup: 'Грудь',
    equipment: 'Блок',
  },
  {
    id: 'pull-up',
    name: 'Подтягивания',
    muscleGroup: 'Спина',
    equipment: 'Собственный вес',
  },
  {
    id: 'lat-pulldown',
    name: 'Вертикальная тяга',
    muscleGroup: 'Спина',
    equipment: 'Блок',
  },
  {
    id: 'seated-row',
    name: 'Горизонтальная тяга',
    muscleGroup: 'Спина',
    equipment: 'Блок',
  },
  {
    id: 'barbell-row',
    name: 'Тяга штанги в наклоне',
    muscleGroup: 'Спина',
    equipment: 'Штанга',
  },
  {
    id: 'one-arm-row',
    name: 'Тяга гантели одной рукой',
    muscleGroup: 'Спина',
    equipment: 'Гантель',
  },
  {
    id: 'back-extension',
    name: 'Гиперэкстензия',
    muscleGroup: 'Разгибатели спины',
    equipment: 'Скамья',
  },
  {
    id: 'back-squat',
    name: 'Приседание со штангой',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Штанга',
  },
  {
    id: 'front-squat',
    name: 'Фронтальный присед',
    muscleGroup: 'Квадрицепс',
    equipment: 'Штанга',
  },
  {
    id: 'hack-squat',
    name: 'Гакк-присед',
    muscleGroup: 'Квадрицепс',
    equipment: 'Тренажёр',
  },
  {
    id: 'leg-press',
    name: 'Жим ногами',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Тренажёр',
  },
  {
    id: 'leg-extension',
    name: 'Разгибание голени',
    muscleGroup: 'Квадрицепс',
    equipment: 'Тренажёр',
  },
  {
    id: 'leg-curl',
    name: 'Сгибание голени',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр',
  },
  {
    id: 'rdl',
    name: 'Румынская тяга',
    muscleGroup: 'Бицепс бедра / ягодицы',
    equipment: 'Штанга',
  },
  {
    id: 'deadlift',
    name: 'Становая тяга',
    muscleGroup: 'Задняя цепь',
    equipment: 'Штанга',
  },
  {
    id: 'hip-thrust',
    name: 'Ягодичный мост',
    muscleGroup: 'Ягодицы',
    equipment: 'Штанга',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Болгарский сплит-присед',
    muscleGroup: 'Ягодицы / квадрицепс',
    equipment: 'Гантели',
  },
  {
    id: 'reverse-lunge',
    name: 'Выпад назад',
    muscleGroup: 'Ягодицы / квадрицепс',
    equipment: 'Гантели',
  },
  {
    id: 'hip-abduction',
    name: 'Отведение бедра в тренажёре',
    muscleGroup: 'Ягодицы',
    equipment: 'Тренажёр',
  },
  {
    id: 'calf-raise',
    name: 'Подъём на носки',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
  },
  {
    id: 'overhead-press',
    name: 'Жим над головой',
    muscleGroup: 'Плечи',
    equipment: 'Штанга',
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Жим гантелей сидя',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
  },
  {
    id: 'lateral-raise',
    name: 'Отведение гантелей в стороны',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
  },
  {
    id: 'rear-delt-fly',
    name: 'Разведение на заднюю дельту',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр',
  },
  {
    id: 'barbell-curl',
    name: 'Сгибание рук со штангой',
    muscleGroup: 'Бицепс',
    equipment: 'Штанга',
  },
  {
    id: 'dumbbell-curl',
    name: 'Сгибание рук с гантелями',
    muscleGroup: 'Бицепс',
    equipment: 'Гантели',
  },
  {
    id: 'hammer-curl',
    name: 'Молотковые сгибания',
    muscleGroup: 'Бицепс / плечевая',
    equipment: 'Гантели',
  },
  {
    id: 'triceps-pushdown',
    name: 'Разгибание рук на блоке',
    muscleGroup: 'Трицепс',
    equipment: 'Блок',
  },
  {
    id: 'overhead-triceps',
    name: 'Разгибание рук из-за головы',
    muscleGroup: 'Трицепс',
    equipment: 'Блок',
  },
  {
    id: 'lying-triceps-extension',
    name: 'Разгибание рук лёжа',
    muscleGroup: 'Трицепс',
    equipment: 'Гантели',
  },
  {
    id: 'crunch',
    name: 'Скручивание',
    muscleGroup: 'Пресс',
    equipment: 'Собственный вес',
  },
  {
    id: 'reverse-crunch',
    name: 'Обратное скручивание',
    muscleGroup: 'Пресс',
    equipment: 'Собственный вес',
  },
  {
    id: 'seated-leg-curl',
    name: 'Сгибание голени сидя',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр',
  },
  {
    id: 'lying-leg-curl',
    name: 'Сгибание голени лёжа',
    muscleGroup: 'Бицепс бедра',
    equipment: 'Тренажёр',
  },
  {
    id: 'incline-curl',
    name: 'Сгибание рук на наклонной скамье',
    muscleGroup: 'Бицепс',
    equipment: 'Гантели',
  },
  {
    id: 'preacher-curl',
    name: 'Сгибание рук на скамье Скотта',
    muscleGroup: 'Бицепс',
    equipment: 'Штанга',
  },
  {
    id: 'cable-pullover',
    name: 'Пулловер на верхнем блоке',
    muscleGroup: 'Спина',
    equipment: 'Блок',
  },
  {
    id: 'chest-supported-row',
    name: 'Тяга с опорой груди',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
  },
  {
    id: 'standing-calf-raise',
    name: 'Подъём на носки стоя',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
  },
  {
    id: 'pec-deck',
    name: 'Сведение рук в тренажёре (бабочка)',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр',
  },
  {
    id: 'smith-incline-press',
    name: 'Жим в Смите на наклонной скамье',
    muscleGroup: 'Грудь',
    equipment: 'Смит',
  },
  {
    id: 'dips',
    name: 'Отжимания на брусьях',
    muscleGroup: 'Грудь / трицепс',
    equipment: 'Собственный вес',
  },
  {
    id: 'assisted-pull-up',
    name: 'Подтягивания в гравитроне',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
  },
  {
    id: 't-bar-row',
    name: 'Тяга Т-грифа с опорой',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
  },
  {
    id: 'smith-squat',
    name: 'Приседание в Смите',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Смит',
  },
  {
    id: 'pendulum-squat',
    name: 'Маятниковый присед',
    muscleGroup: 'Квадрицепс / ягодицы',
    equipment: 'Тренажёр',
  },
  {
    id: 'hip-adduction',
    name: 'Сведение бёдер в тренажёре',
    muscleGroup: 'Приводящие бедра',
    equipment: 'Тренажёр',
  },
  {
    id: 'cable-kickback',
    name: 'Отведение ноги назад в кроссовере',
    muscleGroup: 'Ягодицы',
    equipment: 'Блок',
  },
  {
    id: 'seated-calf-raise',
    name: 'Подъём на носки сидя',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
  },
  {
    id: 'leg-press-calf',
    name: 'Подъём на носки в жиме ногами',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Жим вверх в тренажёре',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр',
  },
  {
    id: 'cable-lateral-raise',
    name: 'Отведение руки на нижнем блоке',
    muscleGroup: 'Плечи',
    equipment: 'Блок',
  },
  {
    id: 'machine-lateral-raise',
    name: 'Отведение рук в тренажёре',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр',
  },
  {
    id: 'reverse-pec-deck',
    name: 'Обратная бабочка',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр',
  },
  {
    id: 'face-pull',
    name: 'Тяга каната к лицу',
    muscleGroup: 'Плечи',
    equipment: 'Блок',
  },
  {
    id: 'cable-curl',
    name: 'Сгибание рук на нижнем блоке',
    muscleGroup: 'Бицепс',
    equipment: 'Блок',
  },
  {
    id: 'bayesian-curl',
    name: 'Сгибание руки на блоке за спиной',
    muscleGroup: 'Бицепс',
    equipment: 'Блок',
  },
  {
    id: 'cable-crunch',
    name: 'Скручивание на блоке',
    muscleGroup: 'Пресс',
    equipment: 'Блок',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Подъём ног в висе',
    muscleGroup: 'Пресс',
    equipment: 'Собственный вес',
  },
];
